language: objective-c  #1
osx_image: xcode8.2 #2
xcode_project: Supermarket Register/Supermarket Register.xcodeproj #3
xcode_scheme: Supermarket Register #4
xcode_sdk: iphonesimulator8.3 #5

script:
    - xcodebuild clean build -sdk iphonesimulator -project Supermarket\ Register/Supermarket\ Register.xcodeproj -scheme Supermarket\ Register CODE_SIGNING_REQUIRED=NO

